// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/tour.proto

package tourpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPublishedToursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishedToursRequest) Reset() {
	*x = GetPublishedToursRequest{}
	mi := &file_proto_tour_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishedToursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishedToursRequest) ProtoMessage() {}

func (x *GetPublishedToursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishedToursRequest.ProtoReflect.Descriptor instead.
func (*GetPublishedToursRequest) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{0}
}

type GetPublishedToursResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tours         []*TourListItem        `protobuf:"bytes,1,rep,name=tours,proto3" json:"tours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishedToursResponse) Reset() {
	*x = GetPublishedToursResponse{}
	mi := &file_proto_tour_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishedToursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishedToursResponse) ProtoMessage() {}

func (x *GetPublishedToursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishedToursResponse.ProtoReflect.Descriptor instead.
func (*GetPublishedToursResponse) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{1}
}

func (x *GetPublishedToursResponse) GetTours() []*TourListItem {
	if x != nil {
		return x.Tours
	}
	return nil
}

type GetPublicTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicTourRequest) Reset() {
	*x = GetPublicTourRequest{}
	mi := &file_proto_tour_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicTourRequest) ProtoMessage() {}

func (x *GetPublicTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicTourRequest.ProtoReflect.Descriptor instead.
func (*GetPublicTourRequest) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{2}
}

func (x *GetPublicTourRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPublicTourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tour          *TourDetails           `protobuf:"bytes,1,opt,name=tour,proto3" json:"tour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicTourResponse) Reset() {
	*x = GetPublicTourResponse{}
	mi := &file_proto_tour_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicTourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicTourResponse) ProtoMessage() {}

func (x *GetPublicTourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicTourResponse.ProtoReflect.Descriptor instead.
func (*GetPublicTourResponse) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{3}
}

func (x *GetPublicTourResponse) GetTour() *TourDetails {
	if x != nil {
		return x.Tour
	}
	return nil
}

type TourListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	DistanceKm    float64                `protobuf:"fixed64,7,opt,name=distanceKm,proto3" json:"distanceKm,omitempty"`
	PublishedAt   string                 `protobuf:"bytes,8,opt,name=publishedAt,proto3" json:"publishedAt,omitempty"`
	Tags          []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourListItem) Reset() {
	*x = TourListItem{}
	mi := &file_proto_tour_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourListItem) ProtoMessage() {}

func (x *TourListItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourListItem.ProtoReflect.Descriptor instead.
func (*TourListItem) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{4}
}

func (x *TourListItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TourListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TourListItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TourListItem) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *TourListItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TourListItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TourListItem) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

func (x *TourListItem) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

func (x *TourListItem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type TourDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	DistanceKm    float64                `protobuf:"fixed64,7,opt,name=distanceKm,proto3" json:"distanceKm,omitempty"`
	PublishedAt   string                 `protobuf:"bytes,8,opt,name=publishedAt,proto3" json:"publishedAt,omitempty"`
	Tags          []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourDetails) Reset() {
	*x = TourDetails{}
	mi := &file_proto_tour_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourDetails) ProtoMessage() {}

func (x *TourDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourDetails.ProtoReflect.Descriptor instead.
func (*TourDetails) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{5}
}

func (x *TourDetails) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TourDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TourDetails) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TourDetails) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *TourDetails) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TourDetails) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TourDetails) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

func (x *TourDetails) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

func (x *TourDetails) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_proto_tour_proto protoreflect.FileDescriptor

const file_proto_tour_proto_rawDesc = "" +
	"\n" +
	"\x10proto/tour.proto\x12\x04tour\"\x1a\n" +
	"\x18GetPublishedToursRequest\"E\n" +
	"\x19GetPublishedToursResponse\x12(\n" +
	"\x05tours\x18\x01 \x03(\v2\x12.tour.TourListItemR\x05tours\"&\n" +
	"\x14GetPublicTourRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\">\n" +
	"\x15GetPublicTourResponse\x12%\n" +
	"\x04tour\x18\x01 \x01(\v2\x11.tour.TourDetailsR\x04tour\"\xf8\x01\n" +
	"\fTourListItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x1e\n" +
	"\n" +
	"distanceKm\x18\a \x01(\x01R\n" +
	"distanceKm\x12 \n" +
	"\vpublishedAt\x18\b \x01(\tR\vpublishedAt\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\"\xf7\x01\n" +
	"\vTourDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x1e\n" +
	"\n" +
	"distanceKm\x18\a \x01(\x01R\n" +
	"distanceKm\x12 \n" +
	"\vpublishedAt\x18\b \x01(\tR\vpublishedAt\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags2\xad\x01\n" +
	"\vTourService\x12T\n" +
	"\x11GetPublishedTours\x12\x1e.tour.GetPublishedToursRequest\x1a\x1f.tour.GetPublishedToursResponse\x12H\n" +
	"\rGetPublicTour\x12\x1a.tour.GetPublicTourRequest\x1a\x1b.tour.GetPublicTourResponseB\x1aZ\x18api-gateway/proto;tourpbb\x06proto3"

var (
	file_proto_tour_proto_rawDescOnce sync.Once
	file_proto_tour_proto_rawDescData []byte
)

func file_proto_tour_proto_rawDescGZIP() []byte {
	file_proto_tour_proto_rawDescOnce.Do(func() {
		file_proto_tour_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tour_proto_rawDesc), len(file_proto_tour_proto_rawDesc)))
	})
	return file_proto_tour_proto_rawDescData
}

var file_proto_tour_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_tour_proto_goTypes = []any{
	(*GetPublishedToursRequest)(nil),  // 0: tour.GetPublishedToursRequest
	(*GetPublishedToursResponse)(nil), // 1: tour.GetPublishedToursResponse
	(*GetPublicTourRequest)(nil),      // 2: tour.GetPublicTourRequest
	(*GetPublicTourResponse)(nil),     // 3: tour.GetPublicTourResponse
	(*TourListItem)(nil),              // 4: tour.TourListItem
	(*TourDetails)(nil),               // 5: tour.TourDetails
}
var file_proto_tour_proto_depIdxs = []int32{
	4, // 0: tour.GetPublishedToursResponse.tours:type_name -> tour.TourListItem
	5, // 1: tour.GetPublicTourResponse.tour:type_name -> tour.TourDetails
	0, // 2: tour.TourService.GetPublishedTours:input_type -> tour.GetPublishedToursRequest
	2, // 3: tour.TourService.GetPublicTour:input_type -> tour.GetPublicTourRequest
	1, // 4: tour.TourService.GetPublishedTours:output_type -> tour.GetPublishedToursResponse
	3, // 5: tour.TourService.GetPublicTour:output_type -> tour.GetPublicTourResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_tour_proto_init() }
func file_proto_tour_proto_init() {
	if File_proto_tour_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tour_proto_rawDesc), len(file_proto_tour_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tour_proto_goTypes,
		DependencyIndexes: file_proto_tour_proto_depIdxs,
		MessageInfos:      file_proto_tour_proto_msgTypes,
	}.Build()
	File_proto_tour_proto = out.File
	file_proto_tour_proto_goTypes = nil
	file_proto_tour_proto_depIdxs = nil
}
