[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*.log
    DB                /fluent-bit/tail/docker.db
    Mem_Buf_Limit     50MB
    Skip_Long_Lines   On
    Refresh_Interval  10
    Tag               docker.*

[FILTER]
    Name                modify
    Match               docker.*
    Add                 service_name unknown
    Add                 container_name unknown

[FILTER]
    Name                lua
    Match               docker.*
    script              /fluent-bit/scripts/docker-metadata.lua
    call                add_docker_metadata

[OUTPUT]
    Name                loki
    Match               docker.*
    Host                loki
    Port                3100
    Labels              job=fluentbit,container_name=$container_name,service_name=$service_name,environment=development
    Line_format         json