// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/tour.proto

package tourpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPublishedToursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishedToursRequest) Reset() {
	*x = GetPublishedToursRequest{}
	mi := &file_proto_tour_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishedToursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishedToursRequest) ProtoMessage() {}

func (x *GetPublishedToursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishedToursRequest.ProtoReflect.Descriptor instead.
func (*GetPublishedToursRequest) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{0}
}

type TourListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	DistanceKm    float64                `protobuf:"fixed64,7,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	PublishedAt   string                 `protobuf:"bytes,8,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	Tags          []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourListItem) Reset() {
	*x = TourListItem{}
	mi := &file_proto_tour_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourListItem) ProtoMessage() {}

func (x *TourListItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourListItem.ProtoReflect.Descriptor instead.
func (*TourListItem) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{1}
}

func (x *TourListItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TourListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TourListItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TourListItem) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *TourListItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TourListItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TourListItem) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

func (x *TourListItem) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

func (x *TourListItem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type GetPublishedToursResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tours         []*TourListItem        `protobuf:"bytes,1,rep,name=tours,proto3" json:"tours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishedToursResponse) Reset() {
	*x = GetPublishedToursResponse{}
	mi := &file_proto_tour_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishedToursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishedToursResponse) ProtoMessage() {}

func (x *GetPublishedToursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishedToursResponse.ProtoReflect.Descriptor instead.
func (*GetPublishedToursResponse) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{2}
}

func (x *GetPublishedToursResponse) GetTours() []*TourListItem {
	if x != nil {
		return x.Tours
	}
	return nil
}

type GetPublicTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicTourRequest) Reset() {
	*x = GetPublicTourRequest{}
	mi := &file_proto_tour_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicTourRequest) ProtoMessage() {}

func (x *GetPublicTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicTourRequest.ProtoReflect.Descriptor instead.
func (*GetPublicTourRequest) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{3}
}

func (x *GetPublicTourRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TourDuration struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransportType   string                 `protobuf:"bytes,1,opt,name=transport_type,json=transportType,proto3" json:"transport_type,omitempty"` // WALKING / CYCLING / CAR / BUS
	DurationMinutes int32                  `protobuf:"varint,2,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TourDuration) Reset() {
	*x = TourDuration{}
	mi := &file_proto_tour_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourDuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourDuration) ProtoMessage() {}

func (x *TourDuration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourDuration.ProtoReflect.Descriptor instead.
func (*TourDuration) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{4}
}

func (x *TourDuration) GetTransportType() string {
	if x != nil {
		return x.TransportType
	}
	return ""
}

func (x *TourDuration) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

type KeyPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyPoint) Reset() {
	*x = KeyPoint{}
	mi := &file_proto_tour_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPoint) ProtoMessage() {}

func (x *KeyPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPoint.ProtoReflect.Descriptor instead.
func (*KeyPoint) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{5}
}

func (x *KeyPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KeyPoint) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KeyPoint) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *KeyPoint) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *KeyPoint) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type PublicTour struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	DistanceKm    float64                `protobuf:"fixed64,7,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	PublishedAt   string                 `protobuf:"bytes,8,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	Tags          []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	Durations     []*TourDuration        `protobuf:"bytes,10,rep,name=durations,proto3" json:"durations,omitempty"`
	KeyPoints     []*KeyPoint            `protobuf:"bytes,11,rep,name=key_points,json=keyPoints,proto3" json:"key_points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicTour) Reset() {
	*x = PublicTour{}
	mi := &file_proto_tour_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicTour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicTour) ProtoMessage() {}

func (x *PublicTour) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicTour.ProtoReflect.Descriptor instead.
func (*PublicTour) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{6}
}

func (x *PublicTour) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PublicTour) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PublicTour) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PublicTour) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *PublicTour) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PublicTour) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PublicTour) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

func (x *PublicTour) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

func (x *PublicTour) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PublicTour) GetDurations() []*TourDuration {
	if x != nil {
		return x.Durations
	}
	return nil
}

func (x *PublicTour) GetKeyPoints() []*KeyPoint {
	if x != nil {
		return x.KeyPoints
	}
	return nil
}

type GetPublicTourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tour          *PublicTour            `protobuf:"bytes,1,opt,name=tour,proto3" json:"tour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicTourResponse) Reset() {
	*x = GetPublicTourResponse{}
	mi := &file_proto_tour_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicTourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicTourResponse) ProtoMessage() {}

func (x *GetPublicTourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicTourResponse.ProtoReflect.Descriptor instead.
func (*GetPublicTourResponse) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{7}
}

func (x *GetPublicTourResponse) GetTour() *PublicTour {
	if x != nil {
		return x.Tour
	}
	return nil
}

var File_proto_tour_proto protoreflect.FileDescriptor

const file_proto_tour_proto_rawDesc = "" +
	"\n" +
	"\x10proto/tour.proto\x12\x04tour\"\x1a\n" +
	"\x18GetPublishedToursRequest\"\xfa\x01\n" +
	"\fTourListItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x1f\n" +
	"\vdistance_km\x18\a \x01(\x01R\n" +
	"distanceKm\x12!\n" +
	"\fpublished_at\x18\b \x01(\tR\vpublishedAt\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\"E\n" +
	"\x19GetPublishedToursResponse\x12(\n" +
	"\x05tours\x18\x01 \x03(\v2\x12.tour.TourListItemR\x05tours\"&\n" +
	"\x14GetPublicTourRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"`\n" +
	"\fTourDuration\x12%\n" +
	"\x0etransport_type\x18\x01 \x01(\tR\rtransportType\x12)\n" +
	"\x10duration_minutes\x18\x02 \x01(\x05R\x0fdurationMinutes\"\x97\x01\n" +
	"\bKeyPoint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\"\xd9\x02\n" +
	"\n" +
	"PublicTour\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x1f\n" +
	"\vdistance_km\x18\a \x01(\x01R\n" +
	"distanceKm\x12!\n" +
	"\fpublished_at\x18\b \x01(\tR\vpublishedAt\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x120\n" +
	"\tdurations\x18\n" +
	" \x03(\v2\x12.tour.TourDurationR\tdurations\x12-\n" +
	"\n" +
	"key_points\x18\v \x03(\v2\x0e.tour.KeyPointR\tkeyPoints\"=\n" +
	"\x15GetPublicTourResponse\x12$\n" +
	"\x04tour\x18\x01 \x01(\v2\x10.tour.PublicTourR\x04tour2\xad\x01\n" +
	"\vTourService\x12T\n" +
	"\x11GetPublishedTours\x12\x1e.tour.GetPublishedToursRequest\x1a\x1f.tour.GetPublishedToursResponse\x12H\n" +
	"\rGetPublicTour\x12\x1a.tour.GetPublicTourRequest\x1a\x1b.tour.GetPublicTourResponseB\x1bZ\x19tour-service/proto;tourpbb\x06proto3"

var (
	file_proto_tour_proto_rawDescOnce sync.Once
	file_proto_tour_proto_rawDescData []byte
)

func file_proto_tour_proto_rawDescGZIP() []byte {
	file_proto_tour_proto_rawDescOnce.Do(func() {
		file_proto_tour_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tour_proto_rawDesc), len(file_proto_tour_proto_rawDesc)))
	})
	return file_proto_tour_proto_rawDescData
}

var file_proto_tour_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_tour_proto_goTypes = []any{
	(*GetPublishedToursRequest)(nil),  // 0: tour.GetPublishedToursRequest
	(*TourListItem)(nil),              // 1: tour.TourListItem
	(*GetPublishedToursResponse)(nil), // 2: tour.GetPublishedToursResponse
	(*GetPublicTourRequest)(nil),      // 3: tour.GetPublicTourRequest
	(*TourDuration)(nil),              // 4: tour.TourDuration
	(*KeyPoint)(nil),                  // 5: tour.KeyPoint
	(*PublicTour)(nil),                // 6: tour.PublicTour
	(*GetPublicTourResponse)(nil),     // 7: tour.GetPublicTourResponse
}
var file_proto_tour_proto_depIdxs = []int32{
	1, // 0: tour.GetPublishedToursResponse.tours:type_name -> tour.TourListItem
	4, // 1: tour.PublicTour.durations:type_name -> tour.TourDuration
	5, // 2: tour.PublicTour.key_points:type_name -> tour.KeyPoint
	6, // 3: tour.GetPublicTourResponse.tour:type_name -> tour.PublicTour
	0, // 4: tour.TourService.GetPublishedTours:input_type -> tour.GetPublishedToursRequest
	3, // 5: tour.TourService.GetPublicTour:input_type -> tour.GetPublicTourRequest
	2, // 6: tour.TourService.GetPublishedTours:output_type -> tour.GetPublishedToursResponse
	7, // 7: tour.TourService.GetPublicTour:output_type -> tour.GetPublicTourResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_tour_proto_init() }
func file_proto_tour_proto_init() {
	if File_proto_tour_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tour_proto_rawDesc), len(file_proto_tour_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tour_proto_goTypes,
		DependencyIndexes: file_proto_tour_proto_depIdxs,
		MessageInfos:      file_proto_tour_proto_msgTypes,
	}.Build()
	File_proto_tour_proto = out.File
	file_proto_tour_proto_goTypes = nil
	file_proto_tour_proto_depIdxs = nil
}
